#!/bin/bash

set -eu

root_dir="${PWD}"

# Inputs
TERMINALBOARD_DIR="${root_dir}/${TERMINALBOARD_DIR:?"\$TERMINALBOARD_DIR not set"}"

: "${CONCOURSE_HOST}"
: "${CONCOURSE_USERNAME}"
: "${CONCOURSE_PASSWORD}"

export GOPATH="${PWD}/gopath"
export PATH="${GOPATH}/bin:${PATH}"

go get github.com/onsi/ginkgo/ginkgo

"${TERMINALBOARD_DIR}/bin/test"
